environment:
  matrix:
    - ARCH: x86
      CYGWIN: C:\Cygwin
      CYGSH: C:\Cygwin\bin\bash -lc
    - ARCH: x86_64
      CYGWIN: C:\Cygwin64
      CYGSH: C:\Cygwin64\bin\bash -lc

clone_folder: c:\home\appveyor\spacefish

install:
  - "%CYGWIN%\\setup-%ARCH%.exe -q -P fish"
  - "%CYGSH% 'curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs git.io/fisherman'"
  - "%CYGSH% 'fish -c \"cd ~/spacefish; and fisher fishtape .\"'"

build: off

test_script:
 - cd c:\projects\spacefish
 - "%CYGSH% 'fish -c \"cd ~/spacefish; and fishtape tests/*.test.fish\"'"
