environment:
  matrix:
    - ARCH: x86
      CYGWIN: C:\Cygwin
      CYGSH: C:\Cygwin\bin\bash -lc
    - ARCH: x86_64
      CYGWIN: C:\Cygwin64
      CYGSH: C:\Cygwin64\bin\bash -lc

install:
  - "%CYGWIN%\\setup-%ARCH%.exe -q -P fish"
  - "%CYGSH% 'curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs git.io/fisherman'"
  - "%CYGSH% 'fish -c \"cd $APPVEYOR_BUILD_FOLDER; and fisher fishtape .\"'"

test_script:
 - "%CYGSH% 'fish -c \"cd $APPVEYOR_BUILD_FOLDER; and fishtape tests/*.test.fish\"'"
