environment:
  matrix:
    - ARCH: x86
      CYGWIN: C:\Cygwin
      CYGSH: C:\Cygwin\bin\bash -lc
    - ARCH: x86_64
      CYGWIN: C:\Cygwin64
      CYGSH: C:\Cygwin64\bin\bash -lc

build_script:
  - "%CYGWIN%\\setup-%ARCH%.exe -q -P curl,git,fish"
  - "%CYGSH% 'curl -Lo ~/.config/fish/functions/fisher.fish --create-dirs git.io/fisherman'"
  - "%CYGSH% 'cd /cygdrive/c/projects/spacefish ; fish -c \'fisher fishtape .\' ; fish-c \'fishtape tests/*.test.fish\''"
