environment:
  matrix:
    - ARCH: x86
      CYGWIN: C:\Cygwin
      CYGSH: C:\Cygwin\bin\bash -lc

install:
  - "%CYGWIN%\\setup-%ARCH%.exe -q -P fish"

build: off

test_script:
 - "%CYGSH% 'fish -c \"cd /cygdrive/c/projects/spacefish; and npm run test\"'"
