trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.x'

- bash: |
      sudo apt-add-repository -y ppa:fish-shell/release-3
      sudo apt-get update
      sudo apt-get install -y fish
  condition: eq( variables['Agent.OS'], 'Linux' )
  displayName: Install Fish on Linux

- bash: brew install fish
  condition: eq( variables['Agent.OS'], 'Darwin' )
  displayName: Install Fish on macOS

- script: npm test